#!/usr/bin/env python3
'''
Exact integer lattice arithmetic for periodic graphs.

Every shift vector attached to an edge of a quotient graph is an element of
Z^d, and almost every step of the Systre algorithm needs a *canonical* basis
for the sublattice such vectors generate. Floating point is unusable here:
Delgado-Friedrichs & O'Keeffe stress that vertex positions and shifts have to
be handled in exact rational arithmetic because two distinct vertices may sit
arbitrarily close together without being identical
(Acta Cryst. A59, 351-360, doi:10.1107/S0108767303012017, section 4).

The canonical basis used throughout is the row-style **Hermite Normal Form**.
For a set of generators written as the rows of an integer matrix M, the HNF is
the unique matrix H with

    H = U M,    U unimodular (det U = +/-1),

such that H is in row echelon form, every pivot is strictly positive, and each
entry above a pivot is reduced into the half-open interval [0, pivot).
Uniqueness is what makes it usable as a canonical form; see the "deterministic
basis for the integral span" required by Algorithm 5 of Delgado-Friedrichs,
*Barycentric Drawings of Periodic Graphs*, Graph Drawing (GD 2003),
Lecture Notes in Computer Science 2912, 178-189, Springer (2004), page 187.

**references:**
    Delgado-Friedrichs, O. & O'Keeffe, M. (2003). Acta Cryst. A59, 351-360.
        doi:10.1107/S0108767303012017
    Delgado-Friedrichs, O. (2004). Graph Drawing (GD 2003), LNCS 2912, 178-189.
    Bachem, A. & Kannan, R. (1979). SIAM J. Computing 8, 499-507.
        (polynomial-time Hermite normal form)
'''
from __future__ import annotations

from fractions import Fraction
from math import gcd
from collections.abc import Iterable, Sequence

IntVec = tuple[int, ...]


def _ext_gcd(a: int, b: int) -> tuple[int, int, int]:
    '''
    Extended Euclidean algorithm.

    Returns (g, x, y) with g = gcd(a, b) >= 0 and

        g = x * a + y * b

    **parameters:**
        - a: int
        - b: int

    **returns:**
        tuple
            (g, x, y)
    '''
    old_r, r = a, b
    old_s, s = 1, 0
    old_t, t = 0, 1
    while r != 0:
        q = old_r // r
        old_r, r = r, old_r - q * r
        old_s, s = s, old_s - q * s
        old_t, t = t, old_t - q * t
    if old_r < 0:
        old_r, old_s, old_t = -old_r, -old_s, -old_t
    return old_r, old_s, old_t


def _reduce_rows(rows: list[list[int]], ncols: int) -> list[list[int]]:
    '''
    Hermite normal form of `rows`, by extended-gcd elimination.

    **parameters:**
        - rows: list
            Integer rows. The list is reordered and its rows replaced, so a
            caller must not rely on it afterwards.

        - ncols: int
            Width of every row.

    **returns:**
        list
            The non-zero echelon rows.
    '''
    pivot_row = 0
    for col in range(ncols):
        pivot = None
        for i in range(pivot_row, len(rows)):
            if rows[i][col] != 0:
                pivot = i
                break
        if pivot is None:
            continue
        rows[pivot_row], rows[pivot] = rows[pivot], rows[pivot_row]
        for i in range(pivot_row + 1, len(rows)):
            if rows[i][col] == 0:
                continue
            a, b = rows[pivot_row][col], rows[i][col]
            g, x, y = _ext_gcd(a, b)
            top = [x * rows[pivot_row][k] + y * rows[i][k] for k in range(ncols)]
            bot = [(-b // g) * rows[pivot_row][k] + (a // g) * rows[i][k] for k in range(ncols)]
            rows[pivot_row], rows[i] = top, bot
        if rows[pivot_row][col] < 0:
            rows[pivot_row] = [-v for v in rows[pivot_row]]
        piv_val = rows[pivot_row][col]
        for i in range(pivot_row):
            q = rows[i][col] // piv_val
            if q:
                rows[i] = [rows[i][k] - q * rows[pivot_row][k] for k in range(ncols)]
        pivot_row += 1
        if pivot_row == len(rows):
            break

    return [r for r in rows[:pivot_row] if any(r)]


def hermite_basis(vectors: Iterable[Sequence[int]], ncols: int | None = None) -> list[IntVec]:
    '''
    Canonical basis of the integer lattice generated by `vectors`.

    The returned rows are the non-zero rows of the row-style Hermite Normal
    Form, so they are uniquely determined by the lattice itself and not by the
    order or redundancy of the generators. The number of rows is the rank of
    the lattice, which may be smaller than `ncols` (a 2-periodic net presented
    in a 3-dimensional cell is the usual reason).

    That uniqueness is also what lets the basis be built one generator at a
    time. A vector already in the lattice reduced so far cannot change it, so
    it is skipped, and the elimination is only ever run on `ncols` + 1 rows
    rather than on the whole generating set. It matters because the caller
    that dominates this routine passes one translation per edge, and once the
    rank is full nearly all of them are redundant.

    **parameters:**
        - vectors: iterable
            Iterable of integer sequences, all of the same length.

        - ncols: int or None
            Dimension of the ambient lattice. Inferred from the first vector
            when omitted.

    **returns:**
        list
            List of integer tuples forming the HNF basis, in echelon order.
    '''
    rows = [list(int(x) for x in v) for v in vectors]
    rows = [r for r in rows if any(r)]
    if not rows:
        return []
    if ncols is None:
        ncols = len(rows[0])
    for r in rows:
        if len(r) != ncols:
            raise ValueError("all generator vectors must have the same length")

    basis: list[list[int]] = []
    seen: set[tuple[int, ...]] = set()
    for row in rows:
        key = tuple(row)
        if key in seen:
            continue
        seen.add(key)
        if basis and coords_in_basis(row, basis) is not None:
            continue
        basis = _reduce_rows(basis + [row], ncols)

    return [tuple(r) for r in basis]


def hermite_basis_with_transform(
    vectors: Sequence[Sequence[int]],
    ncols: int | None = None,
) -> tuple[list[IntVec], list[IntVec]]:
    '''
    Hermite basis together with the unimodular transform that produces it.

    Returns rows H and coefficients U with

        H[i] = sum_j U[i][j] * vectors[j],

    so that a caller holding a second, parallel list of vectors can carry it
    through the same change of basis. That is exactly what the canonical form
    needs: the basis is chosen from translations expressed in a traversal's
    own coordinates, while the symmetry computation needs the very same basis
    expressed in the original lattice coordinates.

    Unlike `hermite_basis`, the generating set is passed through untouched:
    zero rows are kept, duplicates are not collapsed and redundant generators
    are not skipped. Any of those would break the correspondence between the
    columns of U and the input list, which is the whole point of the routine.

    **parameters:**
        - vectors: sequence
            Integer generators, all of the same length.

        - ncols: int or None
            Ambient dimension; inferred from the first vector when omitted.

    **returns:**
        tuple
            (basis rows, transform rows). The transform has one column per
            input generator.
    '''
    rows = [list(int(x) for x in v) for v in vectors]
    if not rows:
        return [], []
    if ncols is None:
        ncols = len(rows[0])
    count = len(rows)
    work = [rows[i] + [1 if j == i else 0 for j in range(count)] for i in range(count)]
    width = ncols + count

    pivot_row = 0
    for col in range(ncols):
        pivot = None
        for i in range(pivot_row, len(work)):
            if work[i][col] != 0:
                pivot = i
                break
        if pivot is None:
            continue
        work[pivot_row], work[pivot] = work[pivot], work[pivot_row]
        for i in range(pivot_row + 1, len(work)):
            if work[i][col] == 0:
                continue
            a, b = work[pivot_row][col], work[i][col]
            g, x, y = _ext_gcd(a, b)
            top = [x * work[pivot_row][k] + y * work[i][k] for k in range(width)]
            bot = [(-b // g) * work[pivot_row][k] + (a // g) * work[i][k] for k in range(width)]
            work[pivot_row], work[i] = top, bot
        if work[pivot_row][col] < 0:
            work[pivot_row] = [-v for v in work[pivot_row]]
        piv_val = work[pivot_row][col]
        for i in range(pivot_row):
            q = work[i][col] // piv_val
            if q:
                work[i] = [work[i][k] - q * work[pivot_row][k] for k in range(width)]
        pivot_row += 1
        if pivot_row == len(work):
            break

    basis = [tuple(r[:ncols]) for r in work[:pivot_row]]
    transform = [tuple(r[ncols:]) for r in work[:pivot_row]]
    return basis, transform


def pivot_columns(basis: Sequence[Sequence[int]]) -> list[int]:
    '''
    Column index of the leading non-zero entry of each row of an HNF basis.

    **parameters:**
        - basis: sequence
            Rows of a Hermite basis, in echelon order.

    **returns:**
        list
            One column index per row.
    '''
    cols = []
    for row in basis:
        for j, val in enumerate(row):
            if val != 0:
                cols.append(j)
                break
    return cols


def coords_in_basis(
    vector: Sequence[int],
    basis: Sequence[Sequence[int]],
) -> tuple[int, ...] | None:
    '''
    Express `vector` in an HNF `basis`, exactly and over the integers.

    Solves

        vector = sum_i x_i * basis[i]

    by forward substitution down the echelon pivots. Returns None when the
    vector does not lie in the lattice, which is a meaningful answer rather
    than an error: it is how a supercell edge is detected.

    **parameters:**
        - vector: sequence
            Integer vector to re-express.

        - basis: sequence
            Rows of a Hermite basis, in echelon order.

    **returns:**
        tuple or None
            Integer coordinates, or None when `vector` is not in the lattice.
    '''
    residual = [int(x) for x in vector]
    coords = []
    for row, col in zip(basis, pivot_columns(basis)):
        val = residual[col]
        piv = row[col]
        if val % piv != 0:
            return None
        q = val // piv
        coords.append(q)
        if q:
            for k in range(len(residual)):
                residual[k] -= q * row[k]
    if any(residual):
        return None
    return tuple(coords)


def lattice_index(basis: Sequence[Sequence[int]], ncols: int) -> int | None:
    '''
    Index [Z^n : L] of a full-rank sublattice L given by an HNF basis.

    For an HNF basis the index is simply the product of the pivots, because
    the basis matrix is triangular. A sublattice of index k > 1 means the
    covering graph falls apart into k identical translated copies, which is
    how catenation of a net with itself shows up combinatorially.

    **parameters:**
        - basis: sequence
            Rows of a Hermite basis.

        - ncols: int
            Dimension of the ambient lattice.

    **returns:**
        int or None
            The index, or None when the basis does not have full rank.
    '''
    if len(basis) != ncols:
        return None
    index = 1
    for row, col in zip(basis, pivot_columns(basis)):
        index *= row[col]
    return index


def rational_hermite_basis(
    vectors: Iterable[Sequence[Fraction]],
    ncols: int | None = None,
) -> list[tuple[Fraction, ...]]:
    '''
    Hermite basis of a lattice whose generators are rational, not integral.

    Algorithm 5 accumulates edge shifts in a basis built from edge vectors of
    the barycentric drawing, so the intermediate shifts are rationals even
    though the underlying translation lattice is integral. Scaling by the
    least common multiple of the denominators, reducing over Z and scaling
    back recovers the canonical basis without ever leaving exact arithmetic.

    **parameters:**
        - vectors: iterable
            Iterable of sequences of Fraction.

        - ncols: int or None
            Ambient dimension; inferred from the first vector when omitted.

    **returns:**
        list
            Rows of the canonical basis, as tuples of Fraction.
    '''
    vecs = [tuple(Fraction(x) for x in v) for v in vectors]
    vecs = [v for v in vecs if any(x != 0 for x in v)]
    if not vecs:
        return []
    if ncols is None:
        ncols = len(vecs[0])
    denom = 1
    for vec in vecs:
        for x in vec:
            denom = denom * x.denominator // gcd(denom, x.denominator)
    scaled = [[int(x * denom) for x in vec] for vec in vecs]
    basis = hermite_basis(scaled, ncols)
    return [tuple(Fraction(v, denom) for v in row) for row in basis]


def coords_in_rational_basis(
    vector: Sequence[Fraction],
    basis: Sequence[Sequence[Fraction]],
) -> tuple[int, ...] | None:
    '''
    Express a rational `vector` in a rational HNF `basis` over the integers.

    **parameters:**
        - vector: sequence
            Rational vector to re-express.

        - basis: sequence
            Rows of a rational Hermite basis, in echelon order.

    **returns:**
        tuple or None
            Integer coordinates, or None when the vector is not in the lattice.
    '''
    denom = 1
    for x in list(vector) + [x for row in basis for x in row]:
        frac = Fraction(x)
        denom = denom * frac.denominator // gcd(denom, frac.denominator)
    int_vec = [int(Fraction(x) * denom) for x in vector]
    int_basis = [[int(Fraction(x) * denom) for x in row] for row in basis]
    return coords_in_basis(int_vec, int_basis)


__all__ = [
    "hermite_basis",
    "hermite_basis_with_transform",
    "pivot_columns",
    "coords_in_basis",
    "coords_in_rational_basis",
    "rational_hermite_basis",
    "lattice_index",
]
