#!/usr/bin/env python3
'''
The quotient graph (vector representation) of a periodic net.

A d-periodic net is an infinite graph carrying a free Z^d action by
translations with finitely many vertex and edge orbits. Chung, Hahn & Klee
introduced the finite encoding used here, in which one representative is
chosen per vertex orbit and every edge orbit is written as

    (v_i, v_j, s),   s in Z^d,

meaning "the representative of orbit i is joined to the representative of
orbit j translated by s". Delgado-Friedrichs & O'Keeffe call this the *vector
representation*; the same object viewed as a finite labelled multigraph is the
*quotient graph* or *labelled orbit graph*.

Two facts drive the whole module:

  1. The representation is not unique. Relabelling the orbit representatives,
     translating them, or applying a unimodular change of lattice basis all
     give different integer strings for the same net. Recovering a canonical
     one is the job of `canonical.py`.

  2. The periodicity of the net is *not* the number of columns of s. It is the
     rank of the lattice generated by the shift sums around independent
     cycles. A net drawn in a 3-dimensional cell may be genuinely 2-periodic,
     and that lattice also detects when the given cell is a supercell.

**references:**
    Chung, S. J., Hahn, Th. & Klee, W. E. (1984). Acta Cryst. A40, 42-50.
        (the vector method)
    Delgado-Friedrichs, O. & O'Keeffe, M. (2003). Acta Cryst. A59, 351-360.
        doi:10.1107/S0108767303012017  (sections 2 and 5)
    Delgado-Friedrichs, O. & O'Keeffe, M. (2005). J. Solid State Chem. 178,
        2480-2485. doi:10.1016/j.jssc.2005.06.011  (terminology, section 5)
'''
from __future__ import annotations

from collections import deque
from dataclasses import dataclass
from collections.abc import Iterable, Sequence

from mofstructure.graph_net.lattice import (
    coords_in_basis,
    hermite_basis,
    lattice_index,
)

IntVec = tuple[int, ...]
Edge = tuple[int, int, IntVec]


def _normalise_edge(u: int, v: int, shift: Sequence[int]) -> Edge:
    '''
    Put an edge into a canonical orientation.

    The edge (u, v, s) and the edge (v, u, -s) are the same edge of the net
    seen from its two ends, so exactly one of the two spellings is stored:
    the one with u <= v, and for a self-loop the one whose first non-zero
    shift component is *negative*.

    The sign rule for self-loops is worth spelling out because the published
    pseudocode and the shipped implementation disagree. Algorithm 5 of
    Delgado-Friedrichs (GD 2003, LNCS 2912, page 187) prints

        if v = w and t < 0: set t = -t

    which would store loops with a positive leading component. Every looped
    entry in the RCSR archive that Systre itself writes does the opposite:
    pcu is stored as (-1,0,0), (0,-1,0), (0,0,-1) and fcu as six shifts whose
    leading non-zero component is -1. The archive is the authority here, since
    it is what any key has to be matched against, so the negative convention is
    the one implemented.

    **parameters:**
        - u: int
            Zero-based index of the first vertex orbit.

        - v: int
            Zero-based index of the second vertex orbit.

        - shift: sequence
            Integer translation applied to `v`.

    **returns:**
        tuple
            Normalised (u, v, shift) triple.
    '''
    shift = tuple(int(x) for x in shift)
    if u > v:
        return (v, u, tuple(-x for x in shift))
    if u == v:
        lead = next((x for x in shift if x != 0), 0)
        if lead > 0:
            return (u, v, tuple(-x for x in shift))
    return (u, v, shift)


@dataclass(frozen=True)
class PeriodicGraph:
    '''
    A finite encoding of a periodic net.

    **parameters:**
        - dim: int
            Number of columns of every shift vector, i.e. the rank of the
            translation group used to write the representation down. This is
            an upper bound on the periodicity, not the periodicity itself;
            use `periodicity()` for that.

        - n_vertices: int
            Number of vertex orbits.

        - edges: tuple
            Tuple of normalised (u, v, shift) triples, sorted and deduplicated.

        - name: str or None
            Optional label carried through from the input file.
    '''

    dim: int
    n_vertices: int
    edges: tuple[Edge, ...]
    name: str | None = None

    @classmethod
    def build(
        cls,
        dim: int,
        n_vertices: int,
        edges: Iterable[Sequence],
        name: str | None = None,
    ) -> PeriodicGraph:
        '''
        Construct a graph, normalising and deduplicating the edges.

        A net is a *simple* graph, so two identical (u, v, s) triples describe
        one edge and the duplicate is dropped. A self-loop with zero shift
        joins a vertex to itself in the same unit cell and is not an edge of
        any net, so it is rejected.

        **parameters:**
            - dim: int
                Ambient translation rank.

            - n_vertices: int
                Number of vertex orbits.

            - edges: iterable
                Iterable of (u, v, shift) with zero-based vertex indices.

            - name: str or None
                Optional label.

        **returns:**
            PeriodicGraph
        '''
        seen = set()
        for item in edges:
            u, v, shift = item[0], item[1], tuple(int(x) for x in item[2])
            if len(shift) != dim:
                raise ValueError(f"shift {shift} does not have dimension {dim}")
            if not (0 <= u < n_vertices and 0 <= v < n_vertices):
                raise ValueError(f"edge ({u}, {v}) refers to a vertex outside 0..{n_vertices - 1}")
            if u == v and not any(shift):
                raise ValueError("a self-loop with zero shift is not an edge of a net")
            seen.add(_normalise_edge(u, v, shift))
        return cls(dim=dim, n_vertices=n_vertices, edges=tuple(sorted(seen)), name=name)

    @property
    def n_edges(self) -> int:
        '''
        Number of edge orbits.

        **returns:**
            int
        '''
        return len(self.edges)

    def incidences(self) -> dict[int, list[tuple[int, IntVec]]]:
        '''
        Map each vertex orbit to the images of its neighbours.

        For a vertex v the list holds one (w, s) pair per incident edge end,
        so that the neighbour sits at the image of w translated by s. A
        self-loop contributes two entries, +s and -s, which is what makes the
        degree of a looped vertex come out as two per loop.

        **returns:**
            python dictionary
                Mapping vertex index -> list of (neighbour, shift).
        '''
        inc: dict[int, list[tuple[int, IntVec]]] = {v: [] for v in range(self.n_vertices)}
        for (u, v, shift) in self.edges:
            inc[u].append((v, shift))
            inc[v].append((u, tuple(-x for x in shift)))
        return inc

    def degrees(self) -> list[int]:
        '''
        Coordination number of each vertex orbit.

        Chemists call this the coordination number rather than the degree or
        valency (Delgado-Friedrichs & O'Keeffe 2005, section 2).

        **returns:**
            list
                One integer per vertex orbit.
        '''
        inc = self.incidences()
        return [len(inc[v]) for v in range(self.n_vertices)]

    def is_quotient_connected(self) -> bool:
        '''
        Whether the finite quotient graph is connected.

        This is weaker than connectivity of the infinite net: the quotient can
        be connected while the cover falls apart into translated copies.

        **returns:**
            bool
        '''
        if self.n_vertices <= 1:
            return True
        inc = self.incidences()
        seen = {0}
        stack = [0]
        while stack:
            v = stack.pop()
            for (w, _) in inc[v]:
                if w not in seen:
                    seen.add(w)
                    stack.append(w)
        return len(seen) == self.n_vertices

    def spanning_tree(self) -> tuple[dict[int, IntVec], list[IntVec]]:
        '''
        Breadth-first spanning tree potentials and the resulting cycle vectors.

        Each vertex v of a connected quotient graph is assigned the
        accumulated translation q(v) reached along tree edges from vertex 0,
        with q(0) = 0. Every edge (u, v, s) that is not a tree edge then closes
        a cycle whose net translation is

            c = q(u) + s - q(v).

        The set of all such c generates the translation lattice of the net.
        This is the standard cycle-space construction behind the genus of a
        quotient graph (Delgado-Friedrichs & O'Keeffe 2005, section 5).

        **returns:**
            tuple
                (potentials, cycle_vectors) where potentials maps vertex index
                to its accumulated translation.
        '''
        zero = (0,) * self.dim
        inc = self.incidences()
        potentials: dict[int, IntVec] = {0: zero}
        tree_edges = set()
        queue = deque([0])
        while queue:
            v = queue.popleft()
            for idx, (w, shift) in enumerate(inc[v]):
                if w in potentials:
                    continue
                potentials[w] = tuple(potentials[v][k] + shift[k] for k in range(self.dim))
                tree_edges.add((v, idx))
                queue.append(w)

        cycles: list[IntVec] = []
        used = set()
        for (u, v, shift) in self.edges:
            if u not in potentials or v not in potentials:
                continue
            vec = tuple(potentials[u][k] + shift[k] - potentials[v][k] for k in range(self.dim))
            if not any(vec):
                key = (u, v)
                if key in used:
                    cycles.append(vec)
                used.add(key)
                continue
            cycles.append(vec)
        return potentials, cycles

    def translation_lattice(self) -> list[IntVec]:
        '''
        Canonical basis of the lattice of translations realised by the net.

        **returns:**
            list
                Rows of the Hermite basis; its length is the periodicity.
        '''
        _, cycles = self.spanning_tree()
        return hermite_basis(cycles, self.dim)

    def periodicity(self) -> int:
        '''
        Number of independent directions in which the net actually repeats.

        A net written in a 3-dimensional cell whose cycle lattice has rank 2 is
        a 2-periodic net, and Delgado-Friedrichs & O'Keeffe are explicit that
        such a net must not be called 3-dimensional (2005, section 2).

        **returns:**
            int
        '''
        return len(self.translation_lattice())

    def covering_multiplicity(self) -> int | None:
        '''
        Number of translated copies the infinite cover splits into.

        When the cycle lattice L has full rank, the vertices of the cover fall
        into [Z^dim : L] classes that are never joined by an edge, so the net
        drawn in the given cell is that many identical interpenetrating copies.
        An index of 1 means the cover is connected.

        **returns:**
            int or None
                The index, or None when the cycle lattice is rank deficient.
        '''
        return lattice_index(self.translation_lattice(), self.dim)

    def reduced(self) -> PeriodicGraph:
        '''
        Rewrite the shifts in the net's own translation lattice.

        This performs two normalisations at once. A rank-deficient cycle
        lattice is projected onto its own rank, so a 2-periodic net presented
        in a 3-dimensional cell comes back with two-column shifts. A full-rank
        sublattice of index k > 1 is rescaled to index 1, which is what makes
        the representation independent of the cell the caller happened to
        supply and is the reason a 1x1x2 supercell cannot change the answer.

        **returns:**
            PeriodicGraph
                Equivalent graph whose cycle lattice is the full integer
                lattice of its own dimension.
        '''
        basis = self.translation_lattice()
        if not basis:
            return PeriodicGraph(dim=0, n_vertices=self.n_vertices, edges=(), name=self.name)
        if len(basis) == self.dim and lattice_index(basis, self.dim) == 1:
            return self

        potentials, _ = self.spanning_tree()
        new_edges = []
        for (u, v, shift) in self.edges:
            vec = tuple(potentials[u][k] + shift[k] - potentials[v][k] for k in range(self.dim))
            coords = coords_in_basis(vec, basis)
            if coords is None:
                raise ValueError(
                    "edge shift is outside the cycle lattice; the graph is inconsistent"
                )
            new_edges.append((u, v, coords))
        return PeriodicGraph.build(
            dim=len(basis),
            n_vertices=self.n_vertices,
            edges=new_edges,
            name=self.name,
        )

    def components(self) -> list[PeriodicGraph]:
        '''
        Split into the connected components of the quotient graph.

        An interpenetrated or catenated framework deconstructs into several
        disjoint nets, and each has to be identified separately; Systre reports
        them as numbered components. Vertices are renumbered from zero inside
        each component.

        **returns:**
            list
                One PeriodicGraph per component, ordered by smallest original
                vertex index.
        '''
        inc = self.incidences()
        unseen = set(range(self.n_vertices))
        blocks: list[list[int]] = []
        while unseen:
            root = min(unseen)
            block = []
            stack = [root]
            unseen.discard(root)
            while stack:
                v = stack.pop()
                block.append(v)
                for (w, _) in inc[v]:
                    if w in unseen:
                        unseen.discard(w)
                        stack.append(w)
            blocks.append(sorted(block))

        out = []
        for block in blocks:
            index = {v: i for i, v in enumerate(block)}
            member = set(block)
            edges = [
                (index[u], index[v], shift)
                for (u, v, shift) in self.edges
                if u in member and v in member
            ]
            out.append(
                PeriodicGraph.build(
                    dim=self.dim,
                    n_vertices=len(block),
                    edges=edges,
                    name=self.name,
                )
            )
        return out

    def genus(self) -> int:
        '''
        Cyclomatic number of the quotient graph.

        For a connected quotient graph with v vertex orbits and e edge orbits

            genus = 1 + e - v,

        which Beukemann & Klee showed is at least the periodicity n, with
        equality defining the *minimal nets*
        (Delgado-Friedrichs & O'Keeffe 2005, section 5).

        **returns:**
            int
        '''
        return 1 + self.n_edges - self.n_vertices

    def key_string(self) -> str:
        '''
        Serialise as the whitespace-separated integer string used by Systre.

        The layout is the dimension followed by, for each edge, the two
        one-based vertex indices and the shift components. This is the format
        of the `key` records in the RCSR archive; it is only a *canonical* key
        when the graph itself is already in canonical form.

        **returns:**
            str
        '''
        parts = [str(self.dim)]
        for (u, v, shift) in self.edges:
            parts.extend([str(u + 1), str(v + 1)])
            parts.extend(str(x) for x in shift)
        return " ".join(parts)

    @classmethod
    def from_key_string(cls, text: str, name: str | None = None) -> PeriodicGraph:
        '''
        Parse the integer string produced by `key_string`.

        **parameters:**
            - text: str
                Dimension followed by (u, v, shift...) records.

            - name: str or None
                Optional label.

        **returns:**
            PeriodicGraph
        '''
        tokens = text.split()
        if not tokens:
            raise ValueError("empty key string")
        dim = int(tokens[0])
        stride = 2 + dim
        body = tokens[1:]
        if len(body) % stride != 0:
            raise ValueError(f"key body length {len(body)} is not a multiple of {stride}")
        edges = []
        n_vertices = 0
        for i in range(0, len(body), stride):
            u = int(body[i]) - 1
            v = int(body[i + 1]) - 1
            shift = tuple(int(x) for x in body[i + 2:i + stride])
            n_vertices = max(n_vertices, u + 1, v + 1)
            edges.append((u, v, shift))
        return cls.build(dim=dim, n_vertices=n_vertices, edges=edges, name=name)

    def relabelled(self, permutation: Sequence[int]) -> PeriodicGraph:
        '''
        Apply a permutation of the vertex orbits.

        **parameters:**
            - permutation: sequence
                `permutation[i]` is the new index of old vertex i.

        **returns:**
            PeriodicGraph
        '''
        edges = [(permutation[u], permutation[v], shift) for (u, v, shift) in self.edges]
        return PeriodicGraph.build(self.dim, self.n_vertices, edges, self.name)

    def transformed(self, matrix: Sequence[Sequence[int]]) -> PeriodicGraph:
        '''
        Apply a unimodular change of lattice basis to every shift.

        The new shift is `matrix @ shift`. A unimodular matrix leaves the net
        unchanged and only rewrites the representation, so this is the natural
        way to generate equivalent inputs when testing a canonical form.

        **parameters:**
            - matrix: sequence
                Square integer matrix of side `dim`, determinant +/-1.

        **returns:**
            PeriodicGraph
        '''
        edges = []
        for (u, v, shift) in self.edges:
            new = tuple(
                sum(matrix[r][c] * shift[c] for c in range(self.dim))
                for r in range(self.dim)
            )
            edges.append((u, v, new))
        return PeriodicGraph.build(self.dim, self.n_vertices, edges, self.name)

    def translated(self, offsets: dict[int, Sequence[int]]) -> PeriodicGraph:
        '''
        Move individual orbit representatives to other images of themselves.

        Choosing a different representative for vertex orbit v shifts every
        edge end at v, without changing the net. Delgado-Friedrichs & O'Keeffe
        point this out as one of the sources of the infinitely many
        representations a single net admits (2003, section 2).

        **parameters:**
            - offsets: python dictionary
                Mapping vertex index -> integer translation.

        **returns:**
            PeriodicGraph
        '''
        zero = (0,) * self.dim
        edges = []
        for (u, v, shift) in self.edges:
            du = tuple(offsets.get(u, zero))
            dv = tuple(offsets.get(v, zero))
            new = tuple(shift[k] + dv[k] - du[k] for k in range(self.dim))
            edges.append((u, v, new))
        return PeriodicGraph.build(self.dim, self.n_vertices, edges, self.name)


__all__ = ["PeriodicGraph", "Edge", "IntVec"]
